server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dmu?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#≈‰÷√mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.heartoffrederick.pojo

#≈‰÷√∑÷“≥≤Âº˛pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
